name: load_vegetables_firestore
description: "A new Flutter project."
publish_to: 'none'
version: 0.5.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.3.3
  file_picker: ^10.3.3
  go_router: ^16.3.0
  dart_mappable: ^4.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.2.3

flutter:
  uses-material-design: true
